<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 30%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 5px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>

<h2>Random Name Generator</h2>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    
  </tr>
  <?php 
  $conn = mysqli_connect("localhost", "root", "", "random"); // Displaying the names on a list right away. 
  if ($conn-> connect_error){
  	die ("Connection Failed:" .$conn-> connect__error);
  }
  $sql = "SELECT ID, first_name, last_name FROM names ORDER BY RAND() LIMIT 1"; // Selecting first name and last name from database Random table Names
  $result = $conn-> query($sql);

  if ($result-> num_rows > 0){ // if result is - while statement to sort into rows on the html table
  	while ($row = $result-> fetch_assoc()) {
  		echo "<tr><td>" . $row["first_name"] . "</td><td>" . $row["last_name"] ."</td></tr>";
  	}
  	echo "</table>";
  }

  else {
  	echo "0 results"; // echoing results if it doesn't work. 
  }
  $conn-> close();


  function random(){ 


  }

  ?>
 
</table>
</body>
</html>










































<!-- 
<?php
$servername = "localhost";
$username = "root";
$password = "";


try {
    $conn = new PDO("mysql:host=$servername;dbname=Random_Name_Gen", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully"; 
	
    $results = $db->query('SELECT * FROM Random_Name_Gen'); 
	


	} catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
?>



<?php
$servername = "localhost";
$username = "root";
$password = "";

try {
    $conn = new PDO("mysql:host=$servername;dbname=random", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully"; 

    $result = $conn->query("SELECT * FROM names");
    while ($row = $result->fetchObject()) {
    	echo "<br>" . $row->first_name;
    	echo "<br>" . $row->last_name;

    	
    }
} catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
?>

-->